Test scatter 2D example
matplotlib/napari-matplotlib pull request #121
Opened 2023-05-18 11:20 UTC by ruaridhg

- test_scatter.py: Added astronaut image and an inverted *-1 astronaut image to the viewer and made sure both image layers were selected before calling the ScatterWidget
- test_scatter.png added
- scatter.py: Added __init__ to ScatterWidget class to allow self.updates_layers(None) to add the selected layers (shouldn't have an effect on other parts of the code?)

2023-05-31 09:41 UTC, dstansby commented
It looks like you're tackling two different tests in this PR (scatter and features scatter)? Iis one of them working and one of them not? If one of them is working, I'd suggest putting that in a separate PR that we can merge straight away. Then we can keep moving, and it will make this PR easier to debug as it will only be concerned with one test.

2023-05-31 14:54 UTC, ruaridhg commented
#137 solved inconsistent ordering problem. Partially addresses #129 with other behaviour perhaps desired

2023-05-31 16:07 UTC, dstansby requested changes
Looks 👍 overall, but we want to keep the number of layers features scatter takes as input (1), and plot two different features stored on that one layer against each other.

2023-05-31 16:29 UTC, ruaridhg commented on src/napari_matplotlib/scatter.py
> +    n_layers_input = Interval(2, 2)
Okay good to know, it already does that anyway so #129 should be mostly addressed. Just need to check if a 2nd layer needs to be added (even if not needed)

2023-05-31 16:34 UTC, ruaridhg commented on src/napari_matplotlib/scatter.py
> +    n_layers_input = Interval(2, 2)
Only issue remaining is selecting two features in one layer (currently selects the same feature twice to plot against itself)

2023-06-01 14:32 UTC, dstansby requested changes

2023-06-01 14:32 UTC, dstansby commented on src/napari_matplotlib/tests/test_scatter.py
> +    # widget.y_axis_key = y_column
Any reason for this to stay?

2023-06-01 15:22 UTC, dstansby requested changes
I think there's still code that can be removed here (see my suggestions)?

2023-06-01 15:22 UTC, dstansby commented on src/napari_matplotlib/tests/test_scatter.py
> +    # widget.y_axis_key = y_column
```suggestion
```

2023-06-01 15:22 UTC, dstansby commented on src/napari_matplotlib/tests/test_scatter.py
> +def test_features_scatter_widget_2D(make_napari_viewer, astronaut_data):
```suggestion
def test_features_scatter_widget_2D(make_napari_viewer):
```

2023-06-01 15:22 UTC, dstansby commented on src/napari_matplotlib/tests/test_scatter.py
> +    viewer.add_image(astronaut_data[0], **astronaut_data[1], name="astronaut")
```suggestion
```

2023-06-01 15:32 UTC, dstansby commented
One final request (sorry!), could you squash this all into one commit so we don't add any more test figures changes than we need to in the commit history when it's merged into main?

2023-06-01 16:15 UTC, ruaridhg commented
> 

1 last approval hopefully!

2023-06-01 16:35 UTC, dstansby approved these changes

2023-06-01 16:35 UTC, dstansby commented
:shipit:

2023-06-01 16:41 UTC, merged