Take 2: refactor to allow swappable layer selection methods
matplotlib/napari-matplotlib pull request #56
Opened 2022-07-17 15:51 UTC by kevinyamauchi

This PR separates the layer selection code from the canvas base class (``) by defining a new base class called `BaseLayerSelector`. The `BaseLayerSelector` is a base class that defines the API for custom layer selection code. As an example, I have created a new layer selector `LayerWidgetSelector` that allows the user to select the layer to plot from via a combobox. 

This is not a breaking change, as the default values are for selecting via the layer list (the current behavior on `main`).

To do:
- [ ] add tests
- [ ] generalize the `LayerWidgetSelector` to create as many comboboxes as requested by `n_layers_input`.

This PR supercedes #51.

2022-07-17 16:14 UTC, kevinyamauchi commented
Here's an example where the features scatter widget is created with a combobox for selecting the layer:

https://user-images.githubusercontent.com/1120672/179410874-45c44aa2-00a5-428c-9318-a30b359cd01e.mov


<details>
  <summary>Example code</summary>
 
```python
import napari
import numpy as np
from skimage.measure import regionprops_table

from napari_matplotlib.layer_selectors import LayerWidgetSelector
from napari_matplotlib.scatter import FeaturesScatterWidget

# make a test label image
label_image = np.zeros((100, 100), dtype=np.uint16)

label_image[10:20, 10:20] = 1
label_image[50:70, 50:70] = 2

feature_table_1 = regionprops_table(
    label_image, properties=("label", "area", "perimeter")
)
feature_table_1["index"] = feature_table_1["label"]

# make the points data
n_points = 100
points_data = 100 * np.random.random((100, 2))
points_features = {
    "feature_0": np.random.random((n_points,)),
    "feature_1": np.random.random((n_points,)),
    "feature_2": np.random.random((n_points,)),
}

# create the viewer
viewer = napari.Viewer()
viewer.add_labels(label_image, features=feature_table_1)
viewer.add_points(points_data, features=points_features)

# make the scatter widget
scatter_widget = FeaturesScatterWidget(
    napari_viewer=viewer,
    layer_selector=LayerWidgetSelector
)

# make the widget
viewer.window.add_dock_widget(scatter_widget)

if __name__ == "__main__":
    napari.run()
 ```
</details>

What do you think, @dstansby ? Is this worth pursuing? I think this type of abstraction will make it easier for plugin developers to make custom plots for their particular application.
 
Along the same lines, I was chatting with @ianhi and we were thinking we could make a similar API for adding selectors that could be used to link data selections in the plots to actions in the napari viewer (e.g., selecting points from plotted features and highlight/select the relevant data in the napari viewer).

2022-07-17 16:55 UTC, dstansby commented
My initial thoughts are, I don't see what the point of having a layer selector drop down box is? Doesn't this just duplicate the ability to select layers directly in the `napari` UI?

2022-07-17 19:02 UTC, kevinyamauchi commented
Thanks for the quick reply, @dstansby ! From my side, the broader motivation is to decouple the layer selection logic from the base `NapariMPLWidget` to allow plugin developers to more easily use `napari-matplotlib` to build plots for their plugins. While it is true that for some applications, selecting the layer(s) to plot from layer list is sufficent, there are others, where either setting the layer selection programmatically or via another UI element (e.g., combobox) can be useful. For example, sometimes the user needs to do annotations in layer A while interacting with a plot of data from layer B.

With regards to the combobox, that was mostly meant to be an example of how to implement a `LayerSelector`. Personally, I greatly prefer the combobox selection over layer list selection, because I find that users often don't realize which layer is selected via the layer list. That being said, just allowing combobox selection wasn't wasn't my primary motivation for this refactor.

What do you think? Does this use case seem in-scope for this library?

2022-07-17 19:32 UTC, dstansby commented
Thanks for the extra explanation - I think that makes sense!

I am now coming round to the idea of having a combo boxes to select the layers always shown, as agree using the layer selection can be a bit mysterious, and hadn't thought of the use case of selected/plotted layers being different.

Given this, I think implementing `LayerSelector` is a bit overkill in terms of creating base classes etc. I can see three possible ways to select the layers:

1. Use the `napari` layer list
2. Use some custom combo boxes in `napari-matplotlib`
3. Set the layers programmatically

I think 1. is redundant and doesn't need to be supported if 2. is implemented. For 3., setting the layers programatically could just automatically updated the selection in the combo boxes. So I don't think all the boilerplate is needed, (unless you can convince me there's another way of setting layers that I'm missing here 😄) and my preference is to update `NapariMPLWidget` to set up combo boxes for the right number of layers, instead of the approach in this PR.

2022-07-22 07:32 UTC, kevinyamauchi commented
Hey, @dstansby ! I went this route to preserve the existing layer selection via the napari layer list. However, if you are open to deprecating that functionality, I agree it is cleaner to replace it with a widget that autogenerates a combobox for each layer.

I am sorry, I should have made an issue to discuss before making a PR. I got a bit caught up at the SciPy sprints  (the napari and matplotlib sprints were in the same room 😛 )

2022-11-01 16:59 UTC, dstansby commented
👋 just a heads up that I haven't forgotten about this - just low on time to devote to `napari-matplotlib`. In the new year I will have some decidated time to work in `napari-matplotlib`, so will get back to you then 😃

2023-04-19 14:02 UTC, dstansby requested changes
I'm just getting back into `napari-matplotlib`, and have taken a look over this. I've decided replacing selecting layers is the right way to go, see https://github.com/matplotlib/napari-matplotlib/issues/76. In terms of this PR, I'm struggling a bit with the context. I've left inline comments where it would be useful to have some short docstrings explaining the intent of various functions/methods/classes - if you remember, do you think you could add these and I can take another look?

2023-05-31 09:09 UTC, dstansby commented
Given this is quite an old PR, and it will need a lot of rebasing, I'm going to close as inactive. Thanks a lot for opening 🙏  - it inspired a refactor I did to at least separate the Matplotlib canvas and layer selection into two different classes. If you're still interested in this functionality, please do open a new issue or PR in the future!

2023-05-31 09:09 UTC, closed without merging

2023-05-31 12:53 UTC, kevinyamauchi commented
Hey @dstansby . Sorry for the inactivity! Unfortunately I don't think I will have time to come back to this in the near future, so closing it is the right call. Cool to hear about the refactor. Thanks again for the great library!